Module4 task1
htmlacademy-javascript/1247033-keksobooking-21 pull request #3
Opened 2020-11-03 13:16 UTC by EnjoyTWOS

2020-11-04 15:02 UTC, vitali-usik requested changes

2020-11-04 15:02 UTC, vitali-usik commented on js/main.js
> +    }
switch с одним case очень странно, дума можно обойтись if

2020-11-04 15:02 UTC, vitali-usik commented on js/main.js
> +  if (evt.key === `Enter`) {
Enter в константы

2020-11-04 15:02 UTC, vitali-usik commented on js/main.js
> +      adress: `600, 350`,
должны быть одинаковые цифры как и в location?

2020-11-04 20:03 UTC, EnjoyTWOS commented on js/main.js
> +      adress: `600, 350`,
Цифры взяты из задания: 
"address": строка, адрес предложения. Для простоты пусть пока представляет собой запись вида "{{location.x}}, {{location.y}}", например, "600, 350"

2020-11-04 20:06 UTC, EnjoyTWOS commented on js/main.js
> +    }
исправил

2020-11-04 20:06 UTC, EnjoyTWOS commented on js/main.js
> +  if (evt.key === `Enter`) {
исправил

2020-11-04 20:08 UTC, EnjoyTWOS commented on js/main.js
> +      adress: `600, 350`,
исправил

2020-11-05 11:32 UTC, vitali-usik approved these changes

2020-11-05 11:32 UTC, merged