Module4 task2
htmlacademy-javascript/1247033-keksobooking-21 pull request #7
Opened 2020-11-15 16:40 UTC by EnjoyTWOS

2020-11-16 18:36 UTC, vitali-usik requested changes
Не выполнено:
`Добавьте возможность закрытия карточки с подробной информацией по нажатию клавиши Esc`

2020-11-16 18:36 UTC, vitali-usik commented on js/card.js
> +          address: `600, 350`,
???

2020-11-16 18:36 UTC, vitali-usik commented on js/card.js
> +
???

2020-11-16 18:36 UTC, vitali-usik commented on js/form.js
> +    formImages.setAttribute(`accept`, `image/*`);
???

2020-11-16 18:36 UTC, vitali-usik commented on js/form.js
> +    };
Разве весь этот код относится к текущему заданию?

2020-11-16 18:36 UTC, vitali-usik commented on js/map.js
> +  const successHandler = (pins) => {
Обработчики событий должны быть названы единообразно, либо c префиксом on, либо с постфиксом handler

2020-11-16 18:54 UTC, EnjoyTWOS commented on js/form.js
> +    };
ну да, валидация форм - это же это задание

2020-11-16 18:56 UTC, EnjoyTWOS commented on js/map.js
> +  const successHandler = (pins) => {
+

2020-11-16 19:37 UTC, EnjoyTWOS commented
const closeMapCard = () => {
        document.querySelector(`.map__card`).remove();
      };

      const onCloseCardBtnClick = () => {
        closeMapCard();
      };

      mapCardCloseBtn.addEventListener(`click`, onCloseCardBtnClick);

      const onCardIsEsc = (evt) => {
        window.util.isEscapeEvent(evt, onCloseCardBtnClick);
      };
      mapCardCloseBtn.addEventListener(`keydown`, onCardIsEsc);
обработчик на ескейп

2020-11-16 19:53 UTC, vitali-usik commented on js/form.js
> +    };
мой косяк, вижу

2020-11-17 20:18 UTC, vitali-usik commented on js/map.js
> +  const successHandler = (pins) => {
Не исправлено, завернут на проверку

2020-11-17 20:19 UTC, vitali-usik approved these changes

2020-11-17 20:19 UTC, merged